/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ojaso
 */
public class Item_Average_Hub extends javax.swing.JFrame {

    /**
     * Creates new form Item_Average_Hub
     */
    public Item_Average_Hub() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox_Available = new javax.swing.JCheckBox();
        jButton_Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox_Entrees = new javax.swing.JCheckBox();
        jCheckBox_Month = new javax.swing.JCheckBox();
        jCheckBox_Year = new javax.swing.JCheckBox();
        jButton_Next = new javax.swing.JButton();
        jCheckBox_Sides = new javax.swing.JCheckBox();
        jCheckBox_Beverages = new javax.swing.JCheckBox();
        jCheckBox_Dessert = new javax.swing.JCheckBox();
        jCheckBox_Week = new javax.swing.JCheckBox();

        jCheckBox_Available.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_Available.setText("Available");
        jCheckBox_Available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_AvailableActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 100));
        setUndecorated(true);

        jButton_Exit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Exit.setForeground(new java.awt.Color(255, 0, 51));
        jButton_Exit.setText("EXIT");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Item Averages");

        jCheckBox_Entrees.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_Entrees.setText("Entrees");
        jCheckBox_Entrees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_EntreesActionPerformed(evt);
            }
        });

        jCheckBox_Month.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_Month.setText("Month");
        jCheckBox_Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_MonthActionPerformed(evt);
            }
        });

        jCheckBox_Year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_Year.setText("Year");
        jCheckBox_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_YearActionPerformed(evt);
            }
        });

        jButton_Next.setBackground(new java.awt.Color(255, 0, 0));
        jButton_Next.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Next.setText("Next");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        jCheckBox_Sides.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_Sides.setText("Sides");
        jCheckBox_Sides.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_SidesActionPerformed(evt);
            }
        });

        jCheckBox_Beverages.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_Beverages.setText("Beverages");
        jCheckBox_Beverages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_BeveragesActionPerformed(evt);
            }
        });

        jCheckBox_Dessert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_Dessert.setText("Dessert");
        jCheckBox_Dessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_DessertActionPerformed(evt);
            }
        });

        jCheckBox_Week.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_Week.setText("Week");
        jCheckBox_Week.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_WeekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCheckBox_Week, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jCheckBox_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(jCheckBox_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jCheckBox_Entrees, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jCheckBox_Sides, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jCheckBox_Beverages, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox_Dessert, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Year)
                    .addComponent(jCheckBox_Month)
                    .addComponent(jCheckBox_Week))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Entrees)
                    .addComponent(jCheckBox_Sides)
                    .addComponent(jCheckBox_Beverages)
                    .addComponent(jCheckBox_Dessert))
                .addGap(18, 18, 18)
                .addComponent(jButton_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jCheckBox_AvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_AvailableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_AvailableActionPerformed

    private void jCheckBox_EntreesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_EntreesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_EntreesActionPerformed

    private void jCheckBox_MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_MonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_MonthActionPerformed

    private void jCheckBox_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_YearActionPerformed

    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextActionPerformed
        // TODO add your handling code here:
        String time = "";
        String food = "";
        if (jCheckBox_Week.isSelected()){
            time = "week";
        } else if (jCheckBox_Month.isSelected()){
            time = "month";
        } else if (jCheckBox_Year.isSelected()){
            time = "year";
        }
        if (jCheckBox_Entrees.isSelected()){
            food = "entree";
        } else if (jCheckBox_Sides.isSelected()){
            food = "side";
        } else if (jCheckBox_Beverages.isSelected()){
            food = "beverage";
        } else if (jCheckBox_Dessert.isSelected()){
            food = "dessert";
        }
        
        if(!time.equals("") && !food.equals("")){
            this.dispose();
            new Averages(time, food).setVisible(true);
        }
    }//GEN-LAST:event_jButton_NextActionPerformed

    private void jCheckBox_SidesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_SidesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_SidesActionPerformed

    private void jCheckBox_BeveragesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_BeveragesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_BeveragesActionPerformed

    private void jCheckBox_DessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_DessertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_DessertActionPerformed

    private void jCheckBox_WeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_WeekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_WeekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Item_Average_Hub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Item_Average_Hub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Item_Average_Hub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Item_Average_Hub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Item_Average_Hub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_Next;
    private javax.swing.JCheckBox jCheckBox_Available;
    private javax.swing.JCheckBox jCheckBox_Beverages;
    private javax.swing.JCheckBox jCheckBox_Dessert;
    private javax.swing.JCheckBox jCheckBox_Entrees;
    private javax.swing.JCheckBox jCheckBox_Month;
    private javax.swing.JCheckBox jCheckBox_Sides;
    private javax.swing.JCheckBox jCheckBox_Week;
    private javax.swing.JCheckBox jCheckBox_Year;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
