
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ojaso
 */
public class Trends_page extends javax.swing.JFrame {

    /**
     * Creates new form Entrees_page
     */
    public Trends_page() {
        initComponents();
        String [] topEntrees = DatabaseAccess.topEntrees();
        jTextField_Top1.setText(topEntrees[0]);
        jTextField_Top2.setText(topEntrees[1]);
        jTextField_Top3.setText(topEntrees[2]);
        jTextField_Top4.setText(topEntrees[3]);
        String [] trendingUpDown = DatabaseAccess.trends();
        jTextField_Up1.setText(trendingUpDown[0]);
        jTextField_Up2.setText(trendingUpDown[1]);
        jTextField_Down1.setText(trendingUpDown[2]);
        jTextField_Down2.setText(trendingUpDown[3]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_Exit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Top1 = new javax.swing.JTextField();
        jTextField_Top2 = new javax.swing.JTextField();
        jTextField_Top3 = new javax.swing.JTextField();
        jTextField_Top4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Up2 = new javax.swing.JTextField();
        jTextField_Up1 = new javax.swing.JTextField();
        jTextField_Down1 = new javax.swing.JTextField();
        jTextField_Down2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 102));
        setLocation(new java.awt.Point(400, 100));
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Trends");

        jButton_Exit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_Exit.setForeground(new java.awt.Color(255, 0, 51));
        jButton_Exit.setText("EXIT");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Trending Up:");

        jTextField_Top1.setEditable(false);
        jTextField_Top1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Top1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Top1ActionPerformed(evt);
            }
        });

        jTextField_Top2.setEditable(false);
        jTextField_Top2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Top2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Top2ActionPerformed(evt);
            }
        });

        jTextField_Top3.setEditable(false);
        jTextField_Top3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Top3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Top3ActionPerformed(evt);
            }
        });

        jTextField_Top4.setEditable(false);
        jTextField_Top4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Top4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Top4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Trending Down");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Top 4 entrees that should be available:");

        jTextField_Up2.setEditable(false);
        jTextField_Up2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Up2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Up2ActionPerformed(evt);
            }
        });

        jTextField_Up1.setEditable(false);
        jTextField_Up1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Up1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Up1ActionPerformed(evt);
            }
        });

        jTextField_Down1.setEditable(false);
        jTextField_Down1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Down1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Down1ActionPerformed(evt);
            }
        });

        jTextField_Down2.setEditable(false);
        jTextField_Down2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Down2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Down2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Up2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_Top3, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_Top4, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_Top2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_Top1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_Up1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_Down2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Down1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jLabel9)
                    .addContainerGap(223, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addComponent(jTextField_Top1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Top2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Top3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Top4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Up1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Up2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Down1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Down2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(jLabel9)
                    .addContainerGap(433, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jTextField_Top1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Top1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Top1ActionPerformed

    private void jTextField_Top2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Top2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Top2ActionPerformed

    private void jTextField_Top3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Top3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Top3ActionPerformed

    private void jTextField_Top4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Top4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Top4ActionPerformed

    private void jTextField_Up2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Up2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Up2ActionPerformed

    private void jTextField_Up1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Up1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Up1ActionPerformed

    private void jTextField_Down1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Down1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Down1ActionPerformed

    private void jTextField_Down2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Down2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Down2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrees_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrees_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrees_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrees_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrees_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField_Down1;
    private javax.swing.JTextField jTextField_Down2;
    private javax.swing.JTextField jTextField_Top1;
    private javax.swing.JTextField jTextField_Top2;
    private javax.swing.JTextField jTextField_Top3;
    private javax.swing.JTextField jTextField_Top4;
    private javax.swing.JTextField jTextField_Up1;
    private javax.swing.JTextField jTextField_Up2;
    // End of variables declaration//GEN-END:variables
}
