/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ojaso
 */
public class Add_Condiments extends javax.swing.JFrame {

    /**
     * Creates new form Add_Condiments
     */
    public Add_Condiments() {
        initComponents();
        String[] prices = DatabaseAccess.getPrices("condiments");
        jTextField_C01.setText(String.valueOf(prices[0]));
        jTextField_C02.setText(String.valueOf(prices[1]));
        jTextField_C03.setText(String.valueOf(prices[2]));
        jTextField_C04.setText(String.valueOf(prices[3]));
        jTextField_C05.setText(String.valueOf(prices[4]));
        jTextField_C06.setText(String.valueOf(prices[5]));
        jTextField_C07.setText(String.valueOf(prices[6]));
        jTextField_C08.setText(String.valueOf(prices[7]));
        jTextField_C09.setText(String.valueOf(prices[8]));
        jTextField_C10.setText(String.valueOf(prices[9]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jCheckBox_C01 = new javax.swing.JCheckBox();
        jCheckBox_C10 = new javax.swing.JCheckBox();
        jCheckBox_C02 = new javax.swing.JCheckBox();
        jCheckBox_C03 = new javax.swing.JCheckBox();
        jCheckBox_C06 = new javax.swing.JCheckBox();
        jCheckBox_C07 = new javax.swing.JCheckBox();
        jCheckBox_C05 = new javax.swing.JCheckBox();
        jCheckBox_C08 = new javax.swing.JCheckBox();
        jCheckBox_C09 = new javax.swing.JCheckBox();
        jCheckBox_C04 = new javax.swing.JCheckBox();
        jTextField_C01 = new javax.swing.JTextField();
        jTextField_C10 = new javax.swing.JTextField();
        jTextField_C02 = new javax.swing.JTextField();
        jTextField_C03 = new javax.swing.JTextField();
        jTextField_C04 = new javax.swing.JTextField();
        jTextField_C05 = new javax.swing.JTextField();
        jTextField_C06 = new javax.swing.JTextField();
        jTextField_C07 = new javax.swing.JTextField();
        jTextField_C08 = new javax.swing.JTextField();
        jTextField_C09 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton_Next = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Add Condiments");

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));

        jCheckBox_C01.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_C01.setText("Ketchup");
        jCheckBox_C01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_C01ActionPerformed(evt);
            }
        });

        jCheckBox_C10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_C10.setText("Barbecue Sauce");

        jCheckBox_C02.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_C02.setText("Mustard");

        jCheckBox_C03.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_C03.setText("Mayonnaise");
        jCheckBox_C03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_C03ActionPerformed(evt);
            }
        });

        jCheckBox_C06.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_C06.setText("Onions");

        jCheckBox_C07.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_C07.setText("Lettuce");

        jCheckBox_C05.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_C05.setText("Pickles");

        jCheckBox_C08.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_C08.setText("Tomatoes");

        jCheckBox_C09.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_C09.setText("Jalapenos");
        jCheckBox_C09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_C09ActionPerformed(evt);
            }
        });

        jCheckBox_C04.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_C04.setText("Tartar Sauce");

        jTextField_C01.setEditable(false);
        jTextField_C01.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_C01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_C01ActionPerformed(evt);
            }
        });

        jTextField_C10.setEditable(false);
        jTextField_C10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_C02.setEditable(false);
        jTextField_C02.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_C03.setEditable(false);
        jTextField_C03.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_C04.setEditable(false);
        jTextField_C04.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_C05.setEditable(false);
        jTextField_C05.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_C05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_C05ActionPerformed(evt);
            }
        });

        jTextField_C06.setEditable(false);
        jTextField_C06.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_C07.setEditable(false);
        jTextField_C07.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_C08.setEditable(false);
        jTextField_C08.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_C09.setEditable(false);
        jTextField_C09.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Price:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Price:");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCheckBox_C01, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox_C02, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox_C04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox_C10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jCheckBox_C03, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField_C01, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_C10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_C02, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField_C04, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_C03, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jCheckBox_C08, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox_C09, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox_C07, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox_C05)
                            .addComponent(jCheckBox_C06, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_C06, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_C05, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_C07, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_C08, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_C09, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_C01)
                    .addComponent(jCheckBox_C05)
                    .addComponent(jTextField_C01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_C05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_C06)
                    .addComponent(jCheckBox_C10)
                    .addComponent(jTextField_C10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_C06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_C02)
                    .addComponent(jCheckBox_C07)
                    .addComponent(jTextField_C02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_C07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_C03)
                    .addComponent(jCheckBox_C08)
                    .addComponent(jTextField_C03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_C08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_C04)
                    .addComponent(jCheckBox_C09)
                    .addComponent(jTextField_C04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_C09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton_Next.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Next.setText("Next");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        jButton_Clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Clear.setText("Clear items");
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(298, 298, 298))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 498, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Next)
                    .addComponent(jButton_Clear))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(63, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_C01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_C01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_C01ActionPerformed

    private void jTextField_C01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_C01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_C01ActionPerformed

    private void jTextField_C05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_C05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_C05ActionPerformed

    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextActionPerformed
        String[] prices = DatabaseAccess.getPrices("condiments");
        String[] condimentsID = new String [10];
        for (int i = 0; i < 10; ++i){
            condimentsID[i] = null;
        }
        if (jCheckBox_C01.isSelected() && !jTextField_C01.getText().equals("NA")){
            condimentsID[0] = "C01";
            Order.price += Double.parseDouble(prices[0]);
        }
        if (jCheckBox_C02.isSelected() && !jTextField_C02.getText().equals("NA")){
            condimentsID[1] = "C02";
            Order.price += Double.parseDouble(prices[1]);
        }
        if (jCheckBox_C03.isSelected() && !jTextField_C03.getText().equals("NA")){
            condimentsID[2] = "C03";
            Order.price += Double.parseDouble(prices[2]);
        }
        if (jCheckBox_C04.isSelected() && !jTextField_C04.getText().equals("NA")){
            condimentsID[3] = "C04";
            Order.price += Double.parseDouble(prices[3]);
        }
        if (jCheckBox_C05.isSelected() && !jTextField_C05.getText().equals("NA")){
            condimentsID[4] = "C05";
            Order.price += Double.parseDouble(prices[4]);
        }
        if (jCheckBox_C06.isSelected() && !jTextField_C06.getText().equals("NA")){
            condimentsID[5] = "C06";
            Order.price += Double.parseDouble(prices[5]);
        }
        if (jCheckBox_C07.isSelected() && !jTextField_C07.getText().equals("NA")){
            condimentsID[6] = "C07";
            Order.price += Double.parseDouble(prices[6]);
        }
        if (jCheckBox_C08.isSelected() && !jTextField_C08.getText().equals("NA")){
            condimentsID[7] = "C08";
            Order.price += Double.parseDouble(prices[7]);
        }
        if (jCheckBox_C09.isSelected() && !jTextField_C09.getText().equals("NA")){
            condimentsID[8] = "C09";
            Order.price += Double.parseDouble(prices[8]);
        }
        if (jCheckBox_C10.isSelected() && !jTextField_C10.getText().equals("NA")){
            condimentsID[9] = "C10";
            Order.price += Double.parseDouble(prices[9]);
        }
        
        Order.addCondiments = condimentsID;
        this.dispose();
        new Rm_Condiments().setVisible(true);
    }//GEN-LAST:event_jButton_NextActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jCheckBox_C09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_C09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_C09ActionPerformed

    private void jCheckBox_C03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_C03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_C03ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Condiments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Condiments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Condiments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Condiments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Condiments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Next;
    private javax.swing.JCheckBox jCheckBox_C01;
    private javax.swing.JCheckBox jCheckBox_C02;
    private javax.swing.JCheckBox jCheckBox_C03;
    private javax.swing.JCheckBox jCheckBox_C04;
    private javax.swing.JCheckBox jCheckBox_C05;
    private javax.swing.JCheckBox jCheckBox_C06;
    private javax.swing.JCheckBox jCheckBox_C07;
    private javax.swing.JCheckBox jCheckBox_C08;
    private javax.swing.JCheckBox jCheckBox_C09;
    private javax.swing.JCheckBox jCheckBox_C10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JTextField jTextField_C01;
    private javax.swing.JTextField jTextField_C02;
    private javax.swing.JTextField jTextField_C03;
    private javax.swing.JTextField jTextField_C04;
    private javax.swing.JTextField jTextField_C05;
    private javax.swing.JTextField jTextField_C06;
    private javax.swing.JTextField jTextField_C07;
    private javax.swing.JTextField jTextField_C08;
    private javax.swing.JTextField jTextField_C09;
    private javax.swing.JTextField jTextField_C10;
    // End of variables declaration//GEN-END:variables
}
