
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ojaso
 */
public class Entrees_page extends javax.swing.JFrame {

    /**
     * Creates new form Entrees_page
     */
    public Entrees_page() {
        initComponents();
        String[] prices = DatabaseAccess.getPrices("entree");
        jTextField_E01.setText(String.valueOf(prices[0]));
        jTextField_E02.setText(String.valueOf(prices[1]));
        jTextField_E03.setText(String.valueOf(prices[2]));
        jTextField_E04.setText(String.valueOf(prices[3]));
        jTextField_E05.setText(String.valueOf(prices[4]));
        jTextField_E06.setText(String.valueOf(prices[5]));
        jTextField_E07.setText(String.valueOf(prices[6]));
        jTextField_E08.setText(String.valueOf(prices[7]));
        jTextField_E09.setText(String.valueOf(prices[8]));
        jTextField_E10.setText(String.valueOf(prices[9]));
 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_Next = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox_E01 = new javax.swing.JCheckBox();
        jCheckBox_E04 = new javax.swing.JCheckBox();
        jCheckBox_E07 = new javax.swing.JCheckBox();
        jCheckBox_E02 = new javax.swing.JCheckBox();
        jCheckBox_E05 = new javax.swing.JCheckBox();
        jCheckBox_E08 = new javax.swing.JCheckBox();
        jCheckBox_E03 = new javax.swing.JCheckBox();
        jCheckBox_E06 = new javax.swing.JCheckBox();
        jCheckBox_E09 = new javax.swing.JCheckBox();
        jCheckBox_E10 = new javax.swing.JCheckBox();
        jTextField_E01 = new javax.swing.JTextField();
        jTextField_E04 = new javax.swing.JTextField();
        jTextField_E07 = new javax.swing.JTextField();
        jTextField_E02 = new javax.swing.JTextField();
        jTextField_E10 = new javax.swing.JTextField();
        jTextField_E03 = new javax.swing.JTextField();
        jTextField_E05 = new javax.swing.JTextField();
        jTextField_E08 = new javax.swing.JTextField();
        jTextField_E06 = new javax.swing.JTextField();
        jTextField_E09 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_Clear = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("ENTREES");

        jButton_Next.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Next.setText("Next");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jCheckBox_E01.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_E01.setText("Big Mac");
        jCheckBox_E01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_E01ActionPerformed(evt);
            }
        });

        jCheckBox_E04.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_E04.setText("Bacon Clubhouse Burger");

        jCheckBox_E07.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_E07.setText("Southwest Salad");

        jCheckBox_E02.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_E02.setText("Quarter Pounder with Cheese");

        jCheckBox_E05.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_E05.setText("Buttermilk Crispy Chicken");

        jCheckBox_E08.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_E08.setText("10 pc. McNugget");

        jCheckBox_E03.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_E03.setText("Double Quarter Pounder with Cheese");

        jCheckBox_E06.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_E06.setText("20 pc.McNuggets");

        jCheckBox_E09.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_E09.setText("Caeser Salad");

        jCheckBox_E10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_E10.setText("Crispy Chicken Sandwich");

        jTextField_E01.setEditable(false);
        jTextField_E01.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_E01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_E01ActionPerformed(evt);
            }
        });

        jTextField_E04.setEditable(false);
        jTextField_E04.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_E07.setEditable(false);
        jTextField_E07.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_E02.setEditable(false);
        jTextField_E02.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_E10.setEditable(false);
        jTextField_E10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_E03.setEditable(false);
        jTextField_E03.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_E03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_E03ActionPerformed(evt);
            }
        });

        jTextField_E05.setEditable(false);
        jTextField_E05.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_E08.setEditable(false);
        jTextField_E08.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_E06.setEditable(false);
        jTextField_E06.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_E09.setEditable(false);
        jTextField_E09.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Price:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Price:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCheckBox_E01, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox_E07, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox_E10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox_E04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jCheckBox_E02, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField_E01, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_E04, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_E07, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField_E10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_E02, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_E05, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCheckBox_E06, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox_E09, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox_E08, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox_E03))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField_E03, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_E05, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_E08, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField_E09, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_E06, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField_E03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jTextField_E05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jTextField_E08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_E01)
                            .addComponent(jCheckBox_E03)
                            .addComponent(jTextField_E01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_E05)
                            .addComponent(jCheckBox_E04)
                            .addComponent(jTextField_E04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_E07)
                            .addComponent(jCheckBox_E08)
                            .addComponent(jTextField_E07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_E02)
                            .addComponent(jCheckBox_E06)
                            .addComponent(jTextField_E02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_E06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_E10)
                            .addComponent(jCheckBox_E09)
                            .addComponent(jTextField_E10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_E09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton_Clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Clear.setText("Clear items");
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 333, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(398, 398, 398))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Next)
                    .addComponent(jButton_Clear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_E03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_E03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_E03ActionPerformed

    private void jTextField_E01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_E01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_E01ActionPerformed

    private void jCheckBox_E01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_E01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_E01ActionPerformed

    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextActionPerformed
        String[] prices = DatabaseAccess.getPrices("entree");
        String entreeID = "";
        if (jCheckBox_E01.isSelected() && !jTextField_E01.getText().equals("NA")){
            entreeID = "E01";
            Order.price = Double.parseDouble(prices[0]);
        } else if (jCheckBox_E02.isSelected() && !jTextField_E02.getText().equals("NA")){
            entreeID = "E02";
            Order.price = Double.parseDouble(prices[1]);
        } else if (jCheckBox_E03.isSelected() && !jTextField_E03.getText().equals("NA")){
            entreeID = "E03";
            Order.price = Double.parseDouble(prices[2]);
        } else if (jCheckBox_E04.isSelected() && !jTextField_E04.getText().equals("NA")){
            entreeID = "E04";
            Order.price = Double.parseDouble(prices[3]);
        } else if (jCheckBox_E05.isSelected() && !jTextField_E05.getText().equals("NA")){
            entreeID = "E05";
            Order.price = Double.parseDouble(prices[4]);
        } else if (jCheckBox_E06.isSelected() && !jTextField_E06.getText().equals("NA")){
            entreeID = "E06";
            Order.price = Double.parseDouble(prices[5]);
        } else if (jCheckBox_E07.isSelected() && !jTextField_E07.getText().equals("NA")){
            entreeID = "E07";
            Order.price = Double.parseDouble(prices[6]);
        } else if (jCheckBox_E08.isSelected() && !jTextField_E08.getText().equals("NA")){
            entreeID = "E08";
            Order.price = Double.parseDouble(prices[7]);
        } else if (jCheckBox_E09.isSelected() && !jTextField_E09.getText().equals("NA")){
            entreeID = "E09";
            Order.price = Double.parseDouble(prices[8]);
        } else if (jCheckBox_E10.isSelected() && !jTextField_E10.getText().equals("NA")){
            entreeID = "E10";
            Order.price = Double.parseDouble(prices[9]);
        }
        
        if(!entreeID.equals("")){
            Order.entree = entreeID;
            this.dispose();
            new Add_Condiments().setVisible(true);
        }
    }//GEN-LAST:event_jButton_NextActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrees_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrees_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrees_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrees_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrees_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Next;
    private javax.swing.JCheckBox jCheckBox_E01;
    private javax.swing.JCheckBox jCheckBox_E02;
    private javax.swing.JCheckBox jCheckBox_E03;
    private javax.swing.JCheckBox jCheckBox_E04;
    private javax.swing.JCheckBox jCheckBox_E05;
    private javax.swing.JCheckBox jCheckBox_E06;
    private javax.swing.JCheckBox jCheckBox_E07;
    private javax.swing.JCheckBox jCheckBox_E08;
    private javax.swing.JCheckBox jCheckBox_E09;
    private javax.swing.JCheckBox jCheckBox_E10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField_E01;
    private javax.swing.JTextField jTextField_E02;
    private javax.swing.JTextField jTextField_E03;
    private javax.swing.JTextField jTextField_E04;
    private javax.swing.JTextField jTextField_E05;
    private javax.swing.JTextField jTextField_E06;
    private javax.swing.JTextField jTextField_E07;
    private javax.swing.JTextField jTextField_E08;
    private javax.swing.JTextField jTextField_E09;
    private javax.swing.JTextField jTextField_E10;
    // End of variables declaration//GEN-END:variables
}
