
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ojaso
 */
public class Sides_page extends javax.swing.JFrame {

    /**
     * Creates new form Entrees_page
     */
    public Sides_page() {
        initComponents();
        String[] prices = DatabaseAccess.getPrices("side");
        jTextField_S01.setText(String.valueOf(prices[0]));
        jTextField_S02.setText(String.valueOf(prices[1]));
        jTextField_S03.setText(String.valueOf(prices[2]));
        jTextField_S04.setText(String.valueOf(prices[3]));
        jTextField_S05.setText(String.valueOf(prices[4]));
        jTextField_S06.setText(String.valueOf(prices[5]));
        jTextField_S07.setText(String.valueOf(prices[6]));
        jTextField_S08.setText(String.valueOf(prices[7]));
        jTextField_S09.setText(String.valueOf(prices[8]));
        jTextField_S10.setText(String.valueOf(prices[9]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_Next = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jCheckBox_S01 = new javax.swing.JCheckBox();
        jCheckBox_S04 = new javax.swing.JCheckBox();
        jCheckBox_S02 = new javax.swing.JCheckBox();
        jCheckBox_S03 = new javax.swing.JCheckBox();
        jCheckBox_S05 = new javax.swing.JCheckBox();
        jCheckBox_S06 = new javax.swing.JCheckBox();
        jCheckBox_S07 = new javax.swing.JCheckBox();
        jCheckBox_S08 = new javax.swing.JCheckBox();
        jCheckBox_S09 = new javax.swing.JCheckBox();
        jCheckBox_S10 = new javax.swing.JCheckBox();
        jTextField_S01 = new javax.swing.JTextField();
        jTextField_S02 = new javax.swing.JTextField();
        jTextField_S03 = new javax.swing.JTextField();
        jTextField_S04 = new javax.swing.JTextField();
        jTextField_S05 = new javax.swing.JTextField();
        jTextField_S06 = new javax.swing.JTextField();
        jTextField_S07 = new javax.swing.JTextField();
        jTextField_S08 = new javax.swing.JTextField();
        jTextField_S09 = new javax.swing.JTextField();
        jTextField_S10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 102));
        setLocation(new java.awt.Point(300, 100));
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Sides");

        jButton_Next.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Next.setText("Next");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        jButton_Clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Clear.setText("Clear Items");
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        jCheckBox_S01.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_S01.setText("Donut Sticks");
        jCheckBox_S01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_S01ActionPerformed(evt);
            }
        });

        jCheckBox_S04.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_S04.setText("Large French Fries");
        jCheckBox_S04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_S04ActionPerformed(evt);
            }
        });

        jCheckBox_S02.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_S02.setText("Small French Fries");
        jCheckBox_S02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_S02ActionPerformed(evt);
            }
        });

        jCheckBox_S03.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_S03.setText("Medium French Fries");
        jCheckBox_S03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_S03ActionPerformed(evt);
            }
        });

        jCheckBox_S05.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_S05.setText("Minute Maid Slushie");
        jCheckBox_S05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_S05ActionPerformed(evt);
            }
        });

        jCheckBox_S06.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_S06.setText("Apple Slices");
        jCheckBox_S06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_S06ActionPerformed(evt);
            }
        });

        jCheckBox_S07.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_S07.setText("Small Donut Sticks");
        jCheckBox_S07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_S07ActionPerformed(evt);
            }
        });

        jCheckBox_S08.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_S08.setText("Medium Donut Sticks");
        jCheckBox_S08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_S08ActionPerformed(evt);
            }
        });

        jCheckBox_S09.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_S09.setText("Large Donut Sticks");
        jCheckBox_S09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_S09ActionPerformed(evt);
            }
        });

        jCheckBox_S10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox_S10.setText("Regular Slushie");
        jCheckBox_S10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_S10ActionPerformed(evt);
            }
        });

        jTextField_S01.setEditable(false);
        jTextField_S01.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_S02.setEditable(false);
        jTextField_S02.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_S03.setEditable(false);
        jTextField_S03.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_S04.setEditable(false);
        jTextField_S04.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_S05.setEditable(false);
        jTextField_S05.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_S06.setEditable(false);
        jTextField_S06.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_S07.setEditable(false);
        jTextField_S07.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_S08.setEditable(false);
        jTextField_S08.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_S09.setEditable(false);
        jTextField_S09.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField_S10.setEditable(false);
        jTextField_S10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Price:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(405, 405, 405))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox_S02, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_S03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox_S04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox_S05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox_S01, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField_S02, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_S05, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_S04, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_S03, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_S01, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBox_S10, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_S10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBox_S09)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_S09, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBox_S08)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_S08, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jCheckBox_S07, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_S07, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBox_S06, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(85, 85, 85)
                            .addComponent(jTextField_S06, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_S06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_S06, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_S02, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBox_S07, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_S07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jCheckBox_S03, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox_S08, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_S08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox_S04, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox_S09, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_S09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox_S05, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox_S10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_S10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_S01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_S01, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jTextField_S02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_S03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_S04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jTextField_S05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Next)
                    .addComponent(jButton_Clear))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextActionPerformed
        String[] prices = DatabaseAccess.getPrices("side");
        String sideID = "";
        if (jCheckBox_S01.isSelected() && !jTextField_S01.getText().equals("NA")){
            sideID = "S01";
            Order.price += Double.parseDouble(prices[0]);
        } else if (jCheckBox_S02.isSelected() && !jTextField_S02.getText().equals("NA")){
            sideID = "S02";
            Order.price += Double.parseDouble(prices[1]);
        } else if (jCheckBox_S03.isSelected() && !jTextField_S03.getText().equals("NA")){
            sideID = "S03";
            Order.price += Double.parseDouble(prices[2]);
        } else if (jCheckBox_S04.isSelected() && !jTextField_S04.getText().equals("NA")){
            sideID = "S04";
            Order.price += Double.parseDouble(prices[3]);
        } else if (jCheckBox_S05.isSelected() && !jTextField_S05.getText().equals("NA")){
            sideID = "S05";
            Order.price += Double.parseDouble(prices[4]);
        } else if (jCheckBox_S06.isSelected() && !jTextField_S06.getText().equals("NA")){
            sideID = "S06";
            Order.price += Double.parseDouble(prices[5]);
        } else if (jCheckBox_S07.isSelected() && !jTextField_S07.getText().equals("NA")){
            sideID = "S07";
            Order.price += Double.parseDouble(prices[6]);
        } else if (jCheckBox_S08.isSelected() && !jTextField_S08.getText().equals("NA")){
            sideID = "S08";
            Order.price += Double.parseDouble(prices[7]);
        } else if (jCheckBox_S09.isSelected() && !jTextField_S09.getText().equals("NA")){
            sideID = "S09";
            Order.price += Double.parseDouble(prices[8]);
        } else if (jCheckBox_S10.isSelected() && !jTextField_S10.getText().equals("NA")){
            sideID = "S10";
            Order.price += Double.parseDouble(prices[9]);
        }
        
        if(!sideID.equals("")){
            Order.side = sideID;
            this.dispose();
            new Beverages_page().setVisible(true);
        }
    }//GEN-LAST:event_jButton_NextActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jCheckBox_S01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_S01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_S01ActionPerformed

    private void jCheckBox_S04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_S04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_S04ActionPerformed

    private void jCheckBox_S02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_S02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_S02ActionPerformed

    private void jCheckBox_S03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_S03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_S03ActionPerformed

    private void jCheckBox_S05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_S05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_S05ActionPerformed

    private void jCheckBox_S06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_S06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_S06ActionPerformed

    private void jCheckBox_S07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_S07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_S07ActionPerformed

    private void jCheckBox_S08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_S08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_S08ActionPerformed

    private void jCheckBox_S09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_S09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_S09ActionPerformed

    private void jCheckBox_S10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_S10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_S10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sides_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sides_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sides_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sides_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sides_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Next;
    private javax.swing.JCheckBox jCheckBox_S01;
    private javax.swing.JCheckBox jCheckBox_S02;
    private javax.swing.JCheckBox jCheckBox_S03;
    private javax.swing.JCheckBox jCheckBox_S04;
    private javax.swing.JCheckBox jCheckBox_S05;
    private javax.swing.JCheckBox jCheckBox_S06;
    private javax.swing.JCheckBox jCheckBox_S07;
    private javax.swing.JCheckBox jCheckBox_S08;
    private javax.swing.JCheckBox jCheckBox_S09;
    private javax.swing.JCheckBox jCheckBox_S10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField_S01;
    private javax.swing.JTextField jTextField_S02;
    private javax.swing.JTextField jTextField_S03;
    private javax.swing.JTextField jTextField_S04;
    private javax.swing.JTextField jTextField_S05;
    private javax.swing.JTextField jTextField_S06;
    private javax.swing.JTextField jTextField_S07;
    private javax.swing.JTextField jTextField_S08;
    private javax.swing.JTextField jTextField_S09;
    private javax.swing.JTextField jTextField_S10;
    // End of variables declaration//GEN-END:variables
}
